global:
  logAsJson: true
  ha:
    enabled: true
  mtls:
    enabled: false

dapr_operator:
  # logLevel: debug
  resources:
    limits: 
      cpu: 1000m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

dapr_sidecar_injector:
  # logLevel: debug
  resources:
    limits: 
      cpu: 1000m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 30Mi

dapr_placement:
  # logLevel: debug
  resources:
    limits: 
      cpu: 1000m
      memory: 150Mi
    requests:
      cpu: 250m
      memory: 75Mi

dapr_sentry:
  # logLevel: debug
  resources:
    limits: 
      cpu: 1000m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 30Mi
