global:
  logAsJson: true
  ha:
    enabled: true
  mtls:
    enabled: false

dapr_operator:
  # logLevel: debug
  resources:
    limits: 
      cpu: 1000m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

dapr_sidecar_injector:
  # logLevel: debug
  resources:
    limits: 
      cpu: 1000m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 30Mi

dapr_placement:
  # logLevel: debug
  resources:
    limits: 
      cpu: 1000m
      memory: 150Mi
    requests:
      cpu: 250m
      memory: 75Mi

dapr_sentry:
  # logLevel: debug
  resources:
    limits: 
      cpu: 1000m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 30Mi
  tls:
    issuer:
      # issuer.pem
      certPEM: |
        -----BEGIN CERTIFICATE-----
        MIIClDCCAjmgAwIBAgIUL1DkTKS5qSrOnOwqZuah1dYv7MswCgYIKoZIzj0EAwIw
        eDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMRIwEAYDVQQHDAlEYXBydmlsbGUx
        FzAVBgNVBAoMDmRhcHIuaW8vc2VudHJ5MRcwFQYDVQQLDA5kYXByLmlvL3NlbnRy
        eTEWMBQGA1UEAwwNY2x1c3Rlci5sb2NhbDAeFw0yMzA2MTQyMTIwNDlaFw0zMzA2
        MTEyMTIwNDlaMHgxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJWQTESMBAGA1UEBwwJ
        RGFwcnZpbGxlMRcwFQYDVQQKDA5kYXByLmlvL3NlbnRyeTEXMBUGA1UECwwOZGFw
        ci5pby9zZW50cnkxFjAUBgNVBAMMDWNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIB
        BggqhkjOPQMBBwNCAARTTWROQQVPk3zuM1+R8IwebzC5LTsGaiaF8nLgFz3PhJDz
        whrb1U6DQi+cn1DVwho+uekeML8EXX0JD6DgLjNso4GgMIGdMBIGA1UdEwEB/wQI
        MAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
        BgEFBQcDAjAYBgNVHREEETAPgg1jbHVzdGVyLmxvY2FsMB0GA1UdDgQWBBR4BCg0
        knPnmjbXKJfl0kXlAf10cDAfBgNVHSMEGDAWgBQBIp38I45kg5LpnGM4m6ZSAYRe
        mTAKBggqhkjOPQQDAgNJADBGAiEA0h+xdirFIy72y5SpxyTfitwud4AHfz5cfri/
        DAW+hT8CIQD9SBMu1xO18r7sbQRLNSygK2/o4qb/f1RzocCLJ2YjdQ==
        -----END CERTIFICATE-----
      # issuer.key
      keyPEM: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEILg+6Xxxld7pz9kUnFITHTvgHV8DB2TfIKyWnQJmSPSzoAoGCCqGSM49
        AwEHoUQDQgAEU01kTkEFT5N87jNfkfCMHm8wuS07BmomhfJy4Bc9z4SQ88Ia29VO
        g0IvnJ9Q1cIaPrnpHjC/BF19CQ+g4C4zbA==
        -----END EC PRIVATE KEY-----
    root: 
      # root.pem
      certPEM: |
        -----BEGIN CERTIFICATE-----
        MIICbDCCAhOgAwIBAgIUPArlo1xjBG6931QyC/+8flcmWYEwCgYIKoZIzj0EAwIw
        eDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMRIwEAYDVQQHDAlEYXBydmlsbGUx
        FzAVBgNVBAoMDmRhcHIuaW8vc2VudHJ5MRcwFQYDVQQLDA5kYXByLmlvL3NlbnRy
        eTEWMBQGA1UEAwwNY2x1c3Rlci5sb2NhbDAeFw0yMzA2MTQyMTIwNDlaFw0zMzA2
        MTEyMTIwNDlaMHgxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJWQTESMBAGA1UEBwwJ
        RGFwcnZpbGxlMRcwFQYDVQQKDA5kYXByLmlvL3NlbnRyeTEXMBUGA1UECwwOZGFw
        ci5pby9zZW50cnkxFjAUBgNVBAMMDWNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIB
        BggqhkjOPQMBBwNCAARx9cC1EI+kzkPVxoRKMlpdC/pRujoneHJ85Pkes1AlyN5f
        kkwyaWF0xSqFtrOD1sWSU705vNYvH2G7gDQwjSV+o3sweTAPBgNVHRMBAf8EBTAD
        AQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
        AwIwGAYDVR0RBBEwD4INY2x1c3Rlci5sb2NhbDAdBgNVHQ4EFgQUASKd/COOZIOS
        6ZxjOJumUgGEXpkwCgYIKoZIzj0EAwIDRwAwRAIgfa3mUAQmmjOViI+z1LbBJlab
        KMzJyZ99iZ3MBIKADpgCIA0/Kcy3HAiEy4S7tf0J0/YsBN8xpKWr4A6yReFXiqT/
        -----END CERTIFICATE-----

